name: Build Recovery

on:
  workflow_dispatch:
        
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Configuration
      run: |
        echo MANIFEST: ${{ secrets.MANIFEST }}
        echo MANIFEST_BRANCH: ${{ secrets.MANIFEST_BRANCH }}
        echo DEVICE_TREE: ${{ secrets.DEVICE_TREE }}
        echo DEVICE_TREE_BRANCH: ${{ secrets.DEVICE_TREE_BRANCH }}
        echo DEVICE_PATH: ${{ secrets.DEVICE_PATH }}
        echo MAKEFILE_NAME: ${{ secrets.MAKEFILE_NAME }}
        echo MAKEWHAT: ${{ secrets.MAKEWHAT }}
        echo GH_USERNAME: ${{ secrets.GH_USERNAME }}
        echo GH_EMAIL: ${{ secrets.GH_EMAIL }}

      env:
          MANIFEST: ${{ secrets.MANIFEST }}
          MANIFEST_BRANCH: ${{ secrets.MANIFEST_BRANCH }}
          DEVICE_TREE: ${{ secrets.DEVICE_TREE }}
          DEVICE_TREE_BRANCH: ${{ secrets.DEVICE_TREE_BRANCH }}
          DEVICE_PATH: ${{ secrets.DEVICE_PATH }}
          MAKEFILE_NAME: ${{ secrets.MAKEFILE_NAME }}
          MAKEWHAT: ${{ secrets.MAKEWHAT }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}

    - name: Cleanup
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt -y autoremove --purge
        sudo apt -y autoclean
        sudo apt clean

    - name: Set Swap
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 1024
        swap-size-mb: 10240
        remove-dotnet: 'true'
        temp-reserve-mb: 1024
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 python3

    - name: Install OpenJDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Init Repo
      run: |
        mkdir ${GITHUB_WORKSPACE}/workspace
        cd ${GITHUB_WORKSPACE}/workspace
        git config --global user.name "$GH_USERNAME"
        git config --global user.email "$GH_EMAIL"
        repo init --depth=1 -u $MANIFEST -b $MANIFEST_BRANCH

    - name: Repo Sync
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        repo sync -j4

    - name: Clone Device Tree
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        git clone $DEVICE_TREE -b $DEVICE_TREE_BRANCH ./$DEVICE_PATH
