name: Build recovery

on:
  watch:
    types: [started]

  workflow_dispatch:
        
jobs:
  Build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Cleanup
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt -y autoremove --purge
        sudo apt -y autoclean
        sudo apt clean
        
      env:
          MANIFEST: ${{ secrets.MANIFEST }}
          MANIFEST_BRANCH: ${{ secrets.MANIFEST_BRANCH }}
          DEVICE_TREE: ${{ secrets.DEVICE_TREE }}
          DEVICE_TREE_BRANCH: ${{ secrets.DEVICE_TREE_BRANCH }}
          DEVICE_PATH: ${{ secrets.DEVICE_PATH }}
          MAKEFILE_NAME: ${{ secrets.MAKEFILE_NAME }}
          MAKEWHAT: ${{ secrets.MAKEWHAT }}

    - name: Set Swap
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 1024
        swap-size-mb: 10240
        remove-dotnet: 'true'
        temp-reserve-mb: 1024
        remove-android: 'true'
        remove-haskell: 'true'
